### ISSUE TITLE
should PrivateKey.__init__() do Curve25519 key masking?

### ISSUE THREAD

**Issue by oconnor663** [pyca/pynacl#141]
Curve25519 [requires](https://crypto.stackexchange.com/questions/12425/why-are-the-lower-3-bits-of-curve25519-ed25519-secret-keys-cleared-during-creati) some bits in the secret key to bet set/cleared, and NaCl/libsodium do that clearing automatically when they do curve multiplication. That means that some bits in the input are ignored, and it's possible to have different-looking keys that are functionally the same.

PyNaCl's `PrivateKey.encode()` method isn't aware of this detail; the input bytes are returned exactly as they were given to `__init__()`. So it's possible to have two `PrivateKey` objects that look different but result in the same public key. Here's [an example](https://gist.github.com/oconnor663/aa27fe8cf01e05d1d759).

Should `__init__()` mask the private key before storing it? It's hard for me to imagine this _really_ mattering in practice, but it might be slightly more correct.

**Comment by welshjf** [comment]
IANAC but I don't see any security issue here. The odds of two independently generated keys colliding except for the mask bits are one in 2^252, the same as the key space itself. My thinking is this library should dedicate itself to being a thin Pythonic wrapper, leaving all crypto operations to the underlying libsodium. There, keys are just byte arrays so the same behavior is present if you generate them yourself instead of using `crypto_box_keypair`.

**Comment by lmctv** [comment]
With #320 merged, we provide a means to check  private keys for equivalence. Closing.
