### ISSUE TITLE
Build error: running build_clib     error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by libeclipse** [pyca/pynacl#203]
When doing `pip install pynacl`, I get the following error:

```
...
.linux-aarch64-2.7/nacl/bindings
    copying src/nacl/bindings/randombytes.py -> build/lib.linux-aarch64-2.7/nacl/bindings
    copying src/nacl/bindings/sodium_core.py -> build/lib.linux-aarch64-2.7/nacl/bindings
    running build_clib
    error: [Errno 2] No such file or directory

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-cBHXC5/pynacl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ATMpRl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-cBHXC5/pynacl/
```

Installing on termux on Android 7.0.

**Comment by lynnco** [comment]
Similar issue, looks like a gcc error of some sort?

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating dist-build/Makefile
config.status: creating libsodium.pc
config.status: creating libsodium-uninstalled.pc
config.status: creating msvc-scripts/Makefile
config.status: creating src/Makefile
config.status: creating src/libsodium/Makefile
config.status: creating src/libsodium/include/Makefile
config.status: creating src/libsodium/include/sodium/version.h
config.status: creating test/default/Makefile
config.status: creating test/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
error: [Errno 2] No such file or directory: 'make'
```

**Comment by reaperhulk** [comment]
@lynnco You don't have `make`, which is a requirement for installing on linux. You can get it from your distribution's package manager.

**Comment by lynnco** [comment]
Yea I figured that out a bit ago :/ package manager need a way of specifying dependencies

**Comment by reaperhulk** [comment]
What version of Python and pip? What platform/distro?  Does it happen in a virtualenv? It would be very helpful if we could find a way to make this reproducible in a docker container.

**Comment by nlsantos** [comment]
@awnumar @Routhinator It's a Termux thing.  Install the termux-exec package, and you ought to be able to build it (you might have to restart your termux session before retrying).  Managed to build pynacl (took a few minutes to build on my phone) and Ansible.

@reaperhulk Termux, if you haven't heard of it, is a pretty awesome terminal emulator for Android.  Comes with apt-get plus a thin layer on top.  Includes a lot of essential packages, but not a lot.  And it's missing quite a bit of metadata in packages (build-essential is unknown, for instance).

I thought it was because Termux only bundled BusyBox's install command, but, after reading https://github.com/pyca/pynacl/blob/master/setup.py, I'm pretty sure the error stems from the script's attempt to execute autogen.sh.

Hope this helps.
