### ISSUE TITLE
SecretBox.__unicode__() attribute missing for Py3

### ISSUE THREAD

**Issue by jenstroeger** [pyca/pynacl#205]
Try to `print()` a SecretBox object and you get the following:

```
../python3.4/site-packages/nacl/utils.py", line 54, in __str__
    return self.__unicode__()
AttributeError: 'SecretBox' object has no attribute '__unicode__'
```

**Comment by reaperhulk** [comment]
Okay, looks like this is because SecretBox inherits from StringFixer and that implementation looks like this:

```
class StringFixer(object):

    def __str__(self):
        if six.PY3:
            return self.__unicode__()
        else:
            return self.__bytes__()
```

@dstufft do you remember the rationale for this? I'm not a big fan of people calling `print` on these objects at all, but `__unicode__` is not implemented on any of the objects so in py3 this will fail.

**Comment by dstufft** [comment]
I don't have the slightest idea why that thing exists.

**Comment by reaperhulk** [comment]
Maybe the fix here is to break calling print because that's a bad idea anyway and just entirely remove the StringFixer?

**Comment by dstufft** [comment]
Seems resonable.
