### ISSUE TITLE
Expose Argon2

### ISSUE THREAD

**Issue by maqp** [pyca/pynacl#233]
[Libsodium documentation](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html) states they have included the Password Hashing Competition winner, [Argon2](https://www.cryptolux.org/images/0/0d/Argon2.pdf) and talk about it as "state of the art in the design of memory-hard functions". It would be a valuable addition to this toolkit as it's apparently much better than the current alternatives -- scrypt, bcrypt and PBDKF2-HMAC-SHA256. Please add this to API to allow easy password based encryption of data at rest with PyNaCl.

**Comment by lmctv** [comment]
If nobody beats me at it, I'm willing to add argon2 bindings after #216 and #217 are reviewed and accepted; I was mostly waiting for the import of version 1.0.11 of libsodium, which happened on #225 .

**Comment by maqp** [comment]
@lmctv thank you. While it's not a solution for every version of Python, have you noticed Blake2 (and Keccak/SHA3) was added to Python 3.6s' hashlib?

**Comment by lmctv** [comment]
Yes, I notes both script password hashing and the sha3 competition ones you quoted in #926 .
Still, adding a module to a virtual environment is usually simpler than installing a new version or the interpreter.

**Comment by itdaniher** [comment]
@lmctv currently using `argon2-cffi` _and_ `PyNaCl` - would love to see argon2 exposed!

**Comment by lmctv** [comment]
@itdaniher I'm working on argon2i bindings, but I don't think this should slow down 1.1.0 release.

As an alternative, since both the already integrated scrypt bindings, and the upcoming argon2i ones support the {pwhash}_str and the {pwhash}_verify interfaces using modular crypt() serialization, if you need a serialization format to use on interactive authentication, you could start using ``scrypt..._str`` to serialize the password hashes like in

```python
serialized = nacl.pwhash.scryptsalsa208sha256_str(userpass)
```
and test the serialized format before verification like in

```python
proposed_pass = b'proposed'
if serialized.startswith(b'$7$'):
    res = nacl.pwhash.verify_scryptsalsa208sha256(serialized, proposed_pass)
```
and later replace the serialization with
```python
serialized = nacl.pwhash.argon2i_str(userpass)
```
and add a
```python
elif serialized.startswith(b'$argon2i$'):
    res = nacl.pwhash.verify_argon2i(serialized, proposed_pass)
```
clause to gain argon2i support.

Clearly, if you need a proper Key Derivation Function instead of an hashed password serialization format the solution would be a little more complex.

If you are interested in my work-in-progress branch for the argon2i submittion, it's available at https://github.com/lmctv/pynacl/tree/add-pwhash-argon2i
and I'd be grateful for any review/comment/critique you could provide.

**Comment by itdaniher** [comment]
@lmctv Thanks for the dev cycles and the detailed answer! I'll keep an eye on your branch. Regards!

**Comment by lmctv** [comment]
@itdaniher I've just removed the WIP tag from #261 title. I'd be grateful if you could spare some time for a review. I'd like to know if you'll be able to adapt your existing code to the somewhat limited argon2i API which is exposed by libsodium, and in turn by the bindings I'm proposing to add. Thank you.

**Comment by maqp** [comment]
@lmctv et. al
[Kudos!](https://github.com/pyca/pynacl/commit/70256f7da3fd98d6dcd4c051d1f5221404a7eaf4)
