### ISSUE TITLE
Is there a way to install PyNaCl in Termux?

### ISSUE THREAD

**Issue by markomanninen** [pyca/pynacl#280]
I've tried to install crossbar in Android Termux, but installation halts on PyNaCl  dependency. Is there a way to install PyNaCl in Android/Termux? 

https://termux.com/

**Comment by reaperhulk** [comment]
You'll need a way to compile -- unfortunately I'm unfamiliar with the toolchain here so I don't know where to point you.

**Comment by lmctv** [comment]
From a cursory look at termux-packages on github, it seems the python installation is a very bare-bones  one, providing just the base python system, and no additional packages. I'd suggest you open an issue with termux itself.

**Comment by runningt** [comment]
@markomanninen: Actually I was trying to manually `git clone` pynacl and run `python setup.py install` on termux. The problem seems to be [issue with interpretter path](https://github.com/termux/termux-packages/issues/559) in termux. I was trying to fix that manually using `termux-fix-shebang` script on `configure` but without luck yet.

**Comment by ninioperdido** [comment]
I successfully installed it using termux-chroot (I think is in the package termux-exec). After restarting termux, termux-chroot and pip install pynacl.
