### ISSUE TITLE
Missing "seed" functions

### ISSUE THREAD

**Issue by mitra42** [pyca/pynacl#292]
The "seed" set of functions appear to be missing, the equivalent of box_seed_keypair(xyz) etc. 

This is one of a set of issues that make it hard to do cross-platform crypto between Python and JavaScript (libsodium), both of which have a (different) subset of the bindings. In this case the JS can turn a seed into a PrivateKey/Public key pair, but Python can't, while the Python can create a PrivateKey object from a privatekey, but the JS can't, so there is no simple way that I can see to transfer ownership of objects (possession of the PrivateKey or seed to PrivateKey) from one to the other. (In the previous RSA environment we can export the private key to a file).

**Comment by lmctv** [comment]
@mitra42 @reaperhulk While I don't really understand the reason why different components should share a private-key or its equivalent "seed", adding the low-level binding should be a no-brainer. On the other hand, I'm really reluctant to adding documented API-level bindings unless someone helps me to write some **very harsh** notes explaining seed-sharing is just equivalent to shared-key crypto, and is (almost always) a bad idea.

**Comment by mitra42** [comment]
I appreciate that there are different opinions of how to do crypto. I'll give you the rationale for two cases I'm using this but the meta-problem is that the different bindings  of libsodium implement different subsets making any kind of cross-platform applications really hard because we are limited to the intersection of the sets of ways to use Crypto that you, and the authors of other bindings,  and that makes libsodium a hard choice to build into a framework that has to work in different situations and all our effort goes into working around two different sets of limitations in the bindings, when the underlying functionality is there in the C library (which is what attracted us to libsodium in the first place).

I'm passing private keys around in three cases. 
a) when I want to access things on multiple devices I want one string that can be used to create the private keys. (Ideally the Seed, since it lets me create a Private and a Signing key from a single string). One way I'll build that seed is using the "mnemonic" function in BIP39, (used in BitCoin) but that only works if I can turn it into a single set of bytes that can work on any environment.

b) when I create private resources e.g. a list that will be published, its given a private key for authentication, and a public key for reading, that means I'm managing a lot of private keys, and they live in a resource (a KeyChain) which is itself encrypted with the owner's private key. That means those keys have to be stored in a format that is independent of whether they will be restored on a Python or Javascript (browser) environment. 

c) One reason we create multiple private keys is that a private key is used to convey "ownership" of a resource, eg. the right to authenticate publishing to it, or grant access to it. Sometimes that ownership is shared, i.e. different owners, potentially on different platforms, have to be able to store that key in their own KeyChain. 

While I agree that that sharing my own private key to another person is a bad idea, these cases above are all typical cases of private key crypto, and part of the power of it, and made much harder by the different choices of subsets.

**Comment by lmctv** [comment]
@mitra42 Thank you for the detailed explanation of the use cases you are going after; I promise I'm not going to argue with each of the points you make, but the c) case in particular seems to me a perfect fit for a hierarchy of signing certificates where a master owner key-pair is used to signs the public keys conveying the authorizations to each of the authorized subjects.

As I stated in my first reply, I agree an implementation of box_seed_keypair can be worthwhile[*], but, as a non-native english speaker, I really need help in explaining both the reasons why seed() is present, and the  dangers associated with its use.

[*] And I could as well write the needed dozen of lines myself, especially, since I'm working on the related crypto_box_seal APIs as of now.

**Comment by mitra42** [comment]
Actually "c" won't work as you suggest, since the authorized subjects need the PRIVATE key of the resource to publish.  I'm sure some other implementation could be figured out, but that would probably run into the same issue - that a DIFFERENT subset of functionality is present in the Javascript bindings. 

I didn't realize you weren't a native english speaker (your writing looks too good for that). If you want to send me what you are trying to say I'll be happy to clean it up into better english, I'm just not exactly clear what you are trying to say (and notice that Libsodium itself carries no such warning).

**Comment by lmctv** [comment]
@mitra42  I just created a gist at https://gist.github.com/lmctv/1ce9f81d6dce88a8556d0d64e64acf04 to demostrate how the from_seed API can be implemented using just the already provided APIs
@reaperhulk, @dstufft  since we can add a `PrivateKey.from_seed()` constructor just composing the already existing APIs, I'm unsure if we should prefer adding bindings for libsodium's `crypto_box_curve25519xsalsa20poly1305_seed_keypair()`, or just implement the method as done in the gist.

**Comment by reaperhulk** [comment]
@lmctv If we document a classmethod like that as having identical semantics to the binding I'm fine with that.

**Comment by lmctv** [comment]
Since the binding would be (almost) trivial, I'd like to know if you would object to adding it in the same PR I'm baking to bind SealedBox. My main intent in implementing both from_seed and SealedBox using the high level pynacl APIs was to just show the way the construction really work. In the case of from_seed, I'm ambivalent myself if it's better to keep the python implementation, or at least exploit the temporary hash zeroing libsodium does as soon as a keypad has been generated.

**Comment by reaperhulk** [comment]
pynacl is meant to expose libsodium so I'm fine with exposing (most of) it (excepting GCM, let's not expose that). If it's related to the work you can put it in the same PR, otherwise please do a separate one even though it's a small change!

**Comment by maqp** [comment]
I agree with @lmctv about the dangers of this. The documentation should definitely list suitable use cases as examples, and have huge warnings about not using things like passwords as entropy sources for seeds -- even if it includes hash function, any PBKDF, or a salt.

**Comment by lmctv** [comment]
@maqp I wrote a docstring for the high level construction, and I really think this should be it; I'd rather avoid giving any usage example, or spending any more words (or thought) about what kind of PRF should qualify.

**Comment by lmctv** [comment]
Closing after merge of #317 .
