### ISSUE TITLE
could export more libsodium api to python

### ISSUE THREAD

**Issue by wwqgtxx** [pyca/pynacl#307]
As you write `PyNaCl is a Python binding to libsodium, which is a fork of the Networking and Cryptography library. `, but the `PyNaCl` not export the `crypto_aead` and `crypto_stream` apis from libsodium.
Those two apis are so importent and useful such as `crypto_stream_chacha20_xor` `crypto_stream_chacha20_ietf_xor` `crypto_aead_chacha20poly1305_encrypt` `crypto_aead_chacha20poly1305_ietf_encrypt` `crypto_aead_chacha20poly1305_decrypt` `crypto_aead_chacha20poly1305_ietf_decrypt` can help python program use the `chacha20` `chacha20-ietf` `chacha20-ploy1305` `chacha20-ietf-ploy1305` to encrypt and decrypt.
I know the `SecretBox` api can encrypt and decrypt too, but the `chacha20` and `ploy1305` family cipher used more in other program,so could the author start to support those function.And I see the origin nacl c library was supported stram api [https://nacl.cr.yp.to/stream.html](https://nacl.cr.yp.to/stream.html). It could let the pynacl more useful

**Comment by reaperhulk** [comment]
We're happy to take PRs that expose more functionality as long as they match the binding/high level API style pynacl has developed. `crypto_aead` and  the chacha20poly1305 construct would be great. `crypto_stream` uses xsalsa20 in libsodium, which may be exposed in the future as well.

I'm going to go ahead and close this since we've got most of these as issues already, but I'll open one additional issue to note the request for chacha20poly1305
