### ISSUE TITLE
Pass salt explicitly to argon2di

### ISSUE THREAD

**Issue by boompig** [pyca/pynacl#438]
Is there a way to explicitly pass salt to argon2id?

I don't know too much about how the implementation details of this library, so excuse me if this is wrong. I took a look at `src/bindings/crypto_pwhash.h` and found this function:

But it doesn't look like it takes a salt parameter.

```
int crypto_pwhash_str_alg(char out[128],
                          const char * const passwd,
                          unsigned long long passwdlen,
                          unsigned long long opslimit,
                          size_t memlimit,
                          int alg);
```

Does this mean it's impossible to pass a salt value?

**Comment by lmctv** [comment]
The <algo>.str() methods of all password hashing implementations generate a random salt, as a a means to force avoidance of vulnerabilities stemming from repeated salt usage. If instead of a modular crypt string representation you could use a binary derived key, you can pass a user defined salt to the <algo>.kdf() method, as documented in pynacl docs:

https://pynacl.readthedocs.io/en/stable/password_hashing/#key-derivation
