### ISSUE TITLE
Access to crypto_aead_chacha20poly1305_ietf_* members from libsodium

### ISSUE THREAD

**Issue by pohutukawa** [pyca/pynacl#465]
Hi,

To support RFC-7539 (JOSE JWE using ChaCha20/Poly1305) it's required to gain access to the `crypto_aead_chacha20poly1305_ietf_*` family of members from the underlying C library (`libsodium`). For now, I'm doing that with a 'parallel' `ctypes` wrapper in my code, which seems permissible, though a bit ugly.

There is the desire to support it as well in `python-jose`. But this package has a much larger foot print of usage outside, so there's a much higher demand for cleanliness. See Issue here: https://github.com/mpdavis/python-jose/issues/104

Are there any chances PyNaCl may expose access to those C library namespace members somehow?

**Comment by pohutukawa** [comment]
Note: I suppose an exposure through `nacl.bindings` may be initially already sufficient, as there are no higher level abstractions in PyNaCl building on these.

**Comment by lmctv** [comment]
The #380 PR exposing low level bindings for the whole set of chacha20/poly1305 variants have been merged and is available in pynalc's master branch since commit dc1fa0f40baa3166cfc02320faabef11a725061 .

While waiting for public release of pynacl version 1.3, I think it could be very useful if you tried these bindings to check if the fulfill your requirements.

**Comment by pohutukawa** [comment]
Any indication on when the release of v1.3 will happen? Would be good to adapt the `requirements.txt` files to either point to the git repo or use PyPI.

**Comment by maqp** [comment]
@pohutukawa 1.3 has been released. I think this issue can be closed.
