### ISSUE TITLE
why is sealed box faster than secret box?

### ISSUE THREAD

**Issue by alekibango** [pyca/pynacl#487]
I did some performance testing and it really surprised 
me that SecretBox is as slow as public.Box.

I expect it to be faster than all other alternatives, or at least as fast as SealedBox.

My naive implemetation of MySecretBox using internally SealedBox and one private key would be cca 30 % faster than using internal SecretBox. And that really seems strange to me.

Maybe i am blind to something, but it looks to me that SecretBox implementation is somehow suboptimal.

```py
from nacl.public import (
    PrivateKey, 
    SealedBox)

class MySecretBox:
    """SecretBox implemented using SealedBox, which is 30% faster."""
    def __init__(self, key=None):
        """Initialize using nacl.public.PrivateKey."""
        if key is None:
            self._key = PrivateKey.generate()
        else:
            self._key = key

    def encrypt(self, data):
        return SealedBox(self._key.public_key).encrypt(data)
    
    def decrypt(self, data):
        return SealedBox(self._key).decrypt(data)            
```

**Comment by alekibango** [comment]
if you are interested, here is my little benchmark showing the difference visually (use in jupyter-notebook):
   
  https://gist.github.com/alekibango/87e49733ee475687620adb7a54ac10d3

**Comment by warner** [comment]
Huh, that *is* weird.

(one thing that confused me, but which doesn't address the surprising result, is that your benchmark script isn't measuring the time it takes to construct the `Box` instance. All the (slow) public-key math is done once, during `Box.__init__()`, and it stores the derived (symmetric) session key in the `Box` instance (look for the call to `crypto_box_beforenm()`). So you're comparing the symmetric part of `Box` against the symmetric part of `SecretBox`, and those are exactly the same. That explains why your numbers for `box_enc` and `secret_box_enc` are basically the same, but not why `sealed_box_enc` and `mysecret_box_enc` are faster).

I wasn't able to get jupyter-notebook working, so here's a copy of the results I got locally (encryption time, so lower values are better):

![enc-time](https://user-images.githubusercontent.com/27146/47176701-2114b780-d2cb-11e8-8345-63e75d9928c2.png)

`SealedBox` (which I'm just now learning about, looks nice) has to re-compute a session key for each call to `.encrypt()` or `.decrypt()`, so it cannot amortize that time the same way that `Box` can. But the public-key math only takes about 60 microseconds to run, so it really only makes a difference for short messages. Try re-running your tests with a 1024-byte message and see if you get the results you're expecting.

For much longer messages (like the tens of megabytes your script uses), where the public-key math takes a tiny fraction of the total time, we should expect to see all these flavors take the same time. So yeah, it does sound like something in the symmetric-key handling of `Box` and `SecretBox` is not optimal. Maybe something is copying the message string multiple times? I see that `Box.encrypt` is using `EncryptedMessage._from_parts()`, and is calling `encoder.encode()` on the ciphertext twice, whereas `SealedBox.encrypt` is not using `EncryptedMessage` and is only calling `encode()` once. It looks like `Box` gives you some flexibility about how to manage the generated-or-supplied nonce, whereas `SealedBox` does all the encoding for you (down in the C code).

On a 10MB message, on my machine, `Box.encrypt()` takes 25ms, and `SealedBox.encrypt()` takes 19.7ms. I can save 5ms by commenting out the `encode(nonce + ciphertext)`, and since the default `RawEncoder` does nothing, I think this delay is because of string concatenation (it has to allocate a new 10MB buffer and copy the whole ciphertext into it). We might be able to avoid this overhead by changing `EncryptedMessage` to lazily generate/encode the combined nonce+ciphertext form, using a memoized getter.

I haven't been able to track down the other 5ms yet. Calling the internal `crypto_box_afternm()` function directly takes 14ms, so *something* is consuming an additional 5ms and I don't yet know what. I suspect it's another copy, since the time is about the same.

**Comment by alekibango** [comment]
Thanks for looking into this. 
I need to use this in communicating protocol, which will produce/consume large ammounts of data.
So i am looking into using fastest (pythonic) thing which will be secure enough. 
Yes, for data chunks under 300kB, the measurement looks differently.  I will try to rewrite my script to be more clean and include more and different views on what is interesting.

Thank you for pointing out that box creating might be time consuming too, i almost forgot to think about this. But for most of my usage, it will not be imporant, i will not create that many boxes.

**Comment by alekibango** [comment]
While i was rewriting my benchmarklet+graphs i noticed that my benchmarklet is benchmarking garbage collector more then encryption speed.  Turning off gc changes a lot!  Only public box is much slower now, 
so probably name of my issue was missleading. I will share my notebook source here soon, you might probably close the issue.

**Comment by warner** [comment]
Ah, yeah, I completely forgot about GC.. that might explain it.

**Comment by lmctv** [comment]
@alekibango from what you write in https://github.com/pyca/pynacl/issues/487#issuecomment-432178768 I think this can be closed.
