### ISSUE TITLE
exposing bindings to AEAD AES256-GCM?

### ISSUE THREAD

**Issue by pohutukawa** [pyca/pynacl#515]
There was a ticket  #173 in 2016 towards this, but it has been closed. I was wondering whether that may be considered (again) as `libsodium` provides low level binding support for AES256-GCM with AEAD, and the C header is already available to `pynacl`:

https://github.com/pyca/pynacl/blob/master/src/libsodium/src/libsodium/include/sodium/crypto_aead_aes256gcm.h

For me personally, I'm happy with just the bindings and no further support/integration, as it's just a particular corner case where I need it. So it could be integrated just the same way `nacl.bindings.crypto_aead.crypto_aead_chacha20poly1305_ietf_*crypt()` is supported.

If it helps, I'd be willing to provide a PR for this functionality, exposing those bindings.

**Comment by lmctv** [comment]
Closing, since the main arguments against merging #170 are still valid:
- libsodium's documentation already warns against using aes-256-gcm, and gives the following suggestion: "Unless you absolutely need AES-GCM, use XChaCha20-Poly1305 instead" (https://download.libsodium.org/doc/secret-key_cryptography/aead/aes-256-gcm#warning)
- libsodium is mainly oriented towards implementing djb's algorithms from NaCl (and their direct offsprings like [X]ChaCha20
- libsodium's implementation is limited to x86 CPUs implementing SSE3, aesni and pclmul  (https://download.libsodium.org/doc/secret-key_cryptography/aead/aes-256-gcm#limitations)

Further, the python cryptography project exposes openssl's implementation of AES-GCM (https://cryptography.io/en/latest/hazmat/primitives/aead/?highlight=gcm#cryptography.hazmat.primitives.ciphers.aead.AESGCM), which does work even in absence of the CPU features needed by libsodium's implementation.
