### ISSUE TITLE
``pwhash.*.verify`` raise exceptions when it shouldn't

### ISSUE THREAD

**Issue by wavexx** [pyca/pynacl#519]
The various pwhash.*."verify" methods raise an InvalidkeyError if the passwords do not match. I would have expected such exception to be raised *only* if the supplied hash was invalid for the current function and return False otherwise. Since these functions *imply* a return value, I consider this an API design error.

The generalized nacl.pwhash.verify also raises the same exception (InvalidkeyError) if the hash type is unsupported. This makes it impossible to distinguish between these conditions when using the general method.

**Comment by lmctv** [comment]
As for the password checker raising a exception, it's a explicit choice, already discussed at scrypt implementation times as you can see at https://github.com/pyca/pynacl/pull/204#discussion_r94852785 .
As for the exception raised in case of unknown/unimplemented modular crypt construction, IMHO this is in line with the general practice of limiting the returned details in case of authentication failures, but I think it would be useful if any @pyca/pynacl-core member or @reaperhulk could contribute to this discussion.

**Comment by wavexx** [comment]
On Thu, Mar 21 2019, lmctv wrote:
> As for the password checker raising a exception, it's a explicit
> choice, already discussed at scrypt implementation times as you can
> see at #204 (comment) .

I _really_ don't agree with the discussion above, but I'm not going to
rehash an old discussion.

> As for the exception raised in case of unknown/unimplemented modular
> crypt construction, IMHO this is in line with the general practice of
> limiting the returned details in case of authentication failures, but
> I think it would be useful if any @pyca/pynacl-core member or
> @reaperhulk could contribute to this discussion.

When implementing an authentication backend I need to know if my DB
contains, for whatever reason, an hash function that I cannot verify.
There is likely an implementation issue that I need to log/handle
separately from a mere hash mismatch.

**Comment by reaperhulk** [comment]
These shouldn't be the same exception. There are no real security concerns for "invalid password" vs "I don't know how to dispatch the provided bytes to a verification function". Additionally, we already provide detail in the exception msg that distinguishes them. This does mean that it's possible to extract that and figure out which error it is, albeit in a very ugly way.

https://github.com/pyca/pynacl/blob/01bd892004990db3b941912405ec4d8cda330c77/src/nacl/pwhash/__init__.py#L72-L75

https://github.com/pyca/pynacl/blob/01bd892004990db3b941912405ec4d8cda330c77/src/nacl/bindings/crypto_pwhash.py#L308-L310

Fixing this is a bit tricky since we don't want to break backwards compatibility. Subclassing InvalidkeyError to UnknownHashError is probably what we need. Yuck.

**Comment by lmctv** [comment]
Closing the issue; any further discussion should got to the #521 PR, which should fulfil @wavexx requirement for a way to separately check for unsupported modular crypt format and wrong password.
