### ISSUE TITLE
Failed building wheel for PyNaCl - 

### ISSUE THREAD

**Issue by bobypierre** [pyca/pynacl#522]
Hello, 

Please could you help me if you can, I'm stucked....!!!!....

When I lauch:

 pip install paramiko     or
 pip install PyNaCl         only,
I have this error :
  ----------------------------------------
  Failed building wheel for PyNaCl
  Running setup.py clean for PyNaCl
Failed to build PyNaCl
Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
---------------------------
My system : Android 5.0.1 (My android phone)
I have installed Pydroid 3 on my phone,
I did : pip install pip --upgrade, setuptools,...

but nothing. ....

thanks a lot 
Pierre

**Comment by reaperhulk** [comment]
pynacl requires a compiler and a full C toolchain to compile on platforms where no precompiled wheels are available. As part of that the libsodium configure/make scripts need to know what to do for a given platform, which they may or may not be capable of in your case. Unfortunately we can't provide any help or support getting this working since we don't know anything about what that toolchain looks like in pydroid.

**Comment by bobypierre** [comment]
OK, thanks you very much for your feedback, I'm going to try to go into in deth this. by

**Comment by cjrobbertse** [comment]
Can you help for alpine?

Using this docker image: https://github.com/docker-library/python/blob/0b1fb9529c79ea85b8c80ff3dd85a32a935b0346/3.8/alpine3.10/Dockerfile
