### ISSUE TITLE
Version of cffi >= 1.4 is hard to find; should this be cffi > 1.14?

### ISSUE THREAD

**Issue by paulmromer** [pyca/pynacl#760]
The pytoml.toml file for this project starts with: 

```
[build-system]
# Must be kept in sync with `setup_requirements` in `setup.py`
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "cffi>=1.4.1; python_implementation != 'PyPy'",
]
```

The [the docs for cffi](https://cffi.readthedocs.io/en/latest/whatsnew.html) suggest that 1.15.0 is the most recent version. 

There is also a version `1.14.1` that does not seem to be too old. 

Should the pytoml file have `cffi>=1.14.1` instead of `cffi>=1.4.1`?

**Comment by reaperhulk** [comment]
I'm not sure I understand what the issue is. The definition `cffi>=1.4.1` means that we are compatible with any `cffi` version 1.4.1 or higher. Versions are not compared as integers or decimals, so 1.15 is >= 1.4.1. There is no need to install an old version (and indeed we test against the latest `cffi` in our CI).

**Comment by paulmromer** [comment]
Right. My mistake. Thx.
